# Generated by Django 4.1.1 on 2022-09-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
